learn_yii/protected/models/Courses.php
<?php

/**
 * This is the model class for table "courses".
 *
 * The followings are the available columns in table 'courses':
 * @property integer $course_id
 * @property string $title
 * @property string $description
 */
class Courses extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'courses';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('title', 'required'),
			array('title', 'length', 'max'=>255),
			array('description', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('course_id, title, description', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'course_id' => 'Course Id',
			'title' => 'Название',
			'description' => 'Описание',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('course_id',$this->course_id);
		$criteria->compare('title',$this->title,true);
		$criteria->compare('description',$this->description,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Courses the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

learn_yii/protected/controllers/CourseController.php
<?php

class CourseController extends Controller
{
	public function actionIndex()
	{
		$courses = Courses::model()->findAll();
		$this->render('index', array(
				'courses'=>$courses
				));
	}


	public function actionView( $id )
	{
/*
		if ( !empty($_REQUEST['course_id']) )
		{
			$course_id = Yii::app()->request->getParam('course_id');
		}
*/
//1
			//$lessons = Lessons::model()->findAll("course_id = :course_id", array(":course_id" => $id));
//2
			$criteria=new CDbCriteria;
			$criteria->condition='course_id=:course_id';
			$criteria->params=array(':course_id'=>$id);  // задаем параметры
			$lessons=Lessons::model()->findAll($criteria);

			$course = Courses::model()->find("course_id = :course_id", array(":course_id" => $id));

			$this->render('view', array(
					'lessons'=>$lessons,
					'course'=>$course
					));

	}

	//public function actionAdd()
	//{
/*
    // создаем экземпляр класса модели (Posts)
    $date = new Posts();            
    // поле title заполняем нужным нам значением
    // предполагаеться что title это существующее поле в таблице post
    $date->title = "Заголовок";
    // поле date заполняем текущей датой
    // предполагаеться что title это существующее поле в таблице post
    $date->date     = date("Y-m-d");
    // добавялем в базу. 
    $date->save();   // или $date->insert();
*/
	//}
	public function actionCreate()
	{
		$model=new Courses;
		if(isset($_POST['Courses']))
		{
			$model->attributes=$_POST['Courses'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->course_id));
		}
		$this->render('create',array(
			'model'=>$model,
		));
	}


//updateAll
//updateByPk
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
		if(isset($_POST['Courses']))
		{
			$model->attributes=$_POST['Courses'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->course_id));
		}
		$this->render('update',array(
			'model'=>$model,
		));
	}


//delete
//deleteAll
//deleteByPk
//beforeDelete
//afterDelete
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
	}

	public function loadModel($id)
	{
		$model=Courses::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}


}

learn_yii/protected/controllers/LessonController.php
<?php

class LessonController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			//'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view', 'list'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
//echo "public function actionView($id)";
//echo "<br>";

		$lesson = $this->loadModel($id);
		$course = Courses::model()->find("course_id = :course_id", array(":course_id" => $lesson->course_id));
		$this->render('view',array(
			'model'=>$lesson,
			'course'=>$course,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate(  )
	{
		if ( !empty($_REQUEST['course_id']) )
		{
			$course_id = Yii::app()->request->getParam('course_id');
		}
		else
			$course_id = 0;

		$course = Courses::model()->find("course_id = :course_id", array(":course_id" =>$course_id ));
		$courses = Courses::model()->findAll();
		$list = CHtml::listData( $courses, 'course_id', 'title' );

		$model=new Lessons;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Lessons']))
		{
			$model->attributes=$_POST['Lessons'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->lesson_id));
		}

		$this->render('create',array(
			'model'=>$model,
			'course'=>$course,
			'courses_list'=>$list,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$lesson=$this->loadModel($id);
		$course = Courses::model()->find("course_id = :course_id", array(":course_id" => $lesson->course_id));

		$courses = Courses::model()->findAll();
		//$list = array_values( CHtml::listData($courses, 'course_id', 'title') );
		$list = CHtml::listData( $courses, 'course_id', 'title' );

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Lessons']))
		{
/*
echo "<pre>";
print_r($_REQUEST);
echo "</pre>";
*/
			$lesson->attributes=$_POST['Lessons'];
			if($lesson->save())
				$this->redirect(array('view','id'=>$lesson->lesson_id));
		}

		$this->render('update',array(
			'model'=>$lesson,
			'course'=>$course,
			'courses_list'=>$list,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
//echo "public function actionIndex()";
//echo "<br>";
		$dataProvider=new CActiveDataProvider('Lessons');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Список уроков, не входящих в курсы
	 */
	public function actionList()
	{
//echo "public function actionList()";
//echo "<br>";
		$criteria = new CDbCriteria();
		$criteria->addInCondition('course_id', array('0') );
		$dataProvider=new CActiveDataProvider('Lessons', array('criteria' => $criteria) );
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Lessons('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Lessons']))
			$model->attributes=$_GET['Lessons'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Lessons the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Lessons::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Lessons $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='lessons-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

}//end class

learn_yii/protected/views/course/_form.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'course-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>


	<div class="row">
		<?php echo $form->labelEx($model,'title'); ?>
		<?php echo $form->textField($model,'title',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'title'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'description'); ?>
		<?php echo $form->textArea($model,'description',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'description'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Сохранить' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

learn_yii/protected/views/course/create.php
<?php
/*
$this->breadcrumbs=array(
	'Lessons'=>array('index'),
	'Create',
);
*/
/*
$this->menu=array(
	array('label'=>'List Lessons', 'url'=>array('index')),
	array('label'=>'Manage Lessons', 'url'=>array('admin')),
);
*/
?>

<h1>new course</h1>
<?php $this->renderPartial('_form', array('model'=>$model)); ?>

learn_yii/protected/views/course/index.php
<style>
.table
{
/*background:#2f96b4;*/
/*color: #ffffff;*/
font-size: 150%;
padding: 5px;
}	
.course-action
{
font-size: 75%;
}
</style>
<div class="list-courses">
<h3>List of courses</h3>
	<div>
<p>
	<?php
if ( !Yii::app()->user->isGuest )
{
	echo CHtml::link("add course", array("course/create") );
}
	?>
</p>
	</div>


	<div class="table">
<?php
	foreach ( $courses as $key=>$course )
	{
?>
		<div class="clearfix">
			<div  class="column">
<?php
	echo $key+1;
?>
			</div>
			<div  class="column">
<?php
	echo CHtml::link( $course->title, array("course/view",'id'=>$course->course_id) );
?>
			</div>

<?php
	if ( !Yii::app()->user->isGuest )
	{
?>
			<div  class="column action right">
<?php
	echo CHtml::link( "edit", array("course/update",'id'=>$course->course_id), array('target' => '', 'class' => 'action-link') );
echo " | ";
	echo CHtml::link( "delete course", array("course/delete",'id'=>$course->course_id), array('target' => '', 'class' => 'action-link') );
?>
			</div>
<?php
	}
?>
		</div>

		<div>
<?php
	echo $course->description;
?>
		</div>
<?php
	}//next
?>
	</div>
  
</div>

learn_yii/protected/views/course/update.php
<?php
/*
$this->breadcrumbs=array(
	'Lessons'=>array('index'),
	$model->title=>array('view','id'=>$model->lesson_id),
	'Update',
);
*/
?>

<h1>Edit course "<?php echo $model->title; ?>"</h1>

<?php 
	$this->renderPartial('_form', array('model'=>$model)); 
	echo CHtml::link("Add lesson", array("lesson/create","course_id"=>$model->course_id) );
?>

learn_yii/protected/views/course/view.php
<div>
	<h2><?php echo $course->title; ?></h2>
	<p><?php echo $course->description; ?></p>
</div>
<div class="list-lessons">
<h3>Lesson list</h3>
	<div class="">
<p>
<?php
if ( !Yii::app()->user->isGuest )
{
	echo CHtml::link("Add lesson", array("lesson/create","course_id"=>$course->course_id) );
}
?>
</p>
	</div>

	<div class="table">
<?php
	foreach ( $lessons as $key=>$lesson )
	{
?>
		<div class="clearfix">
			<div  class="column">
<?php
	echo $key+1;
?>
			</div>
			<div  class="column">
<?php
	//echo CHtml::link( $lesson->title, array("lesson/view",'lesson_id'=>$lesson->lesson_id) );
	echo CHtml::link( $lesson->title, array("lesson/view",'id'=>$lesson->lesson_id) );
?>
			</div>

<?php
	if ( !Yii::app()->user->isGuest )
	{
?>
			<div  class="column action right">
<?php
	echo CHtml::link( "edit", array("lesson/update",'id'=>$lesson->lesson_id), array('target' => '', 'class' => 'action-link') );
echo " | ";
	echo CHtml::link( "delete lesson", array("lesson/delete",'id'=>$lesson->lesson_id), array('id' => 'delete-lesson', 'class' => 'action-link') );
?>

			</div>
<?php
	}
?>
		</div>

		<div>
<?php
	echo $lesson->description;
?>
		</div>
<?php
	}
?>
	</div>

</div>