learn_yii/protected/controllers/CourseController.php
<?php

class CourseController extends Controller
{
	public function actionIndex()
	{
		$courses = Courses::model()->findAll();
		$this->render('index', array(
				'courses'=>$courses
				));
	}


	public function actionView( $id )
	{
/*
		if ( !empty($_REQUEST['course_id']) )
		{
			$course_id = Yii::app()->request->getParam('course_id');
		}
*/
//1
			//$lessons = Lessons::model()->findAll("course_id = :course_id", array(":course_id" => $id));
//2
			$criteria=new CDbCriteria;
			$criteria->condition='course_id=:course_id';
			$criteria->params=array(':course_id'=>$id);  // задаем параметры
			$lessons=Lessons::model()->findAll($criteria);

			$course = Courses::model()->find("course_id = :course_id", array(":course_id" => $id));

			$this->render('view', array(
					'lessons'=>$lessons,
					'course'=>$course
					));

	}

	//public function actionAdd()
	//{
/*
    // создаем экземпляр класса модели (Posts)
    $date = new Posts();            
    // поле title заполняем нужным нам значением
    // предполагаеться что title это существующее поле в таблице post
    $date->title = "Заголовок";
    // поле date заполняем текущей датой
    // предполагаеться что title это существующее поле в таблице post
    $date->date     = date("Y-m-d");
    // добавялем в базу. 
    $date->save();   // или $date->insert();
*/
	//}
	public function actionCreate()
	{
		$model=new Courses;
		if(isset($_POST['Courses']))
		{
			$model->attributes=$_POST['Courses'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->course_id));
		}
		$this->render('create',array(
			'model'=>$model,
		));
	}


//updateAll
//updateByPk
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
		if(isset($_POST['Courses']))
		{
			$model->attributes=$_POST['Courses'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->course_id));
		}
		$this->render('update',array(
			'model'=>$model,
		));
	}


//delete
//deleteAll
//deleteByPk
//beforeDelete
//afterDelete
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
	}

	public function loadModel($id)
	{
		$model=Courses::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}


}

learn_yii/protected/controllers/ExportController.php
<?php
class ExportController extends Controller
{
	public $xml_filename;

	public function __construct()
	{
		$this->xml_filename = "export.xml";
		parent::__construct("export");
	}
/*
	public function init() {
	       echo "HELLO";
	   }
*/
	public function actionIndex()
	{
		$this->render("index");
	}

	public function actionExport()
	{
		$courses = Courses::model()->findAll();
		$xml_data["courses"] = $courses;

		$lessons = Lessons::model()->findAll();
		if($lessons===null)
			throw new CHttpException(404,'Error, empty $lessons = Lessons::model()->findAll() .');
		$xml_data["lessons"] = $lessons;

		$xml = "";
		$xml .= "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n";
		$xml .= "<xml_data date-update=\"".date('d.m.Y, H:i')."\">\n";
		$xml .= $this->prep_xml( $xml_data );
		$xml .= "</xml_data>\n";
//echo "<pre>";
//echo htmlspecialchars($xml);
//echo "</pre>";

		if (!empty($xml))
		{
			$this->write_xml( $xml );
		}
		else
		{
			$data['messages'] = "";
			$data['errors'] = "Export error,  empty xml....";
			$params=array('messages'=>$data['messages'],
					'errors'=>$data['errors'],
			);
			$this->render('export',$params);
		}

	}

	private function prep_xml( $xml_data )
	{
//echo "<pre>";
//print_r( $xml_data );
//echo "</pre>";
		$xml = "";
		$xml .= "\t<courses>\n";
		foreach ( $xml_data["courses"] as $key=>$course )
		{
			$xml .= "\t\t<course id=\"" .$course->course_id. "\">\n";
			$xml .= "\t\t\t<title>";
			$xml .= $course->title;
			$xml .= "</title>\n";
			$xml .= "\t\t\t<description>";
			$xml .= $course->description;
			$xml .= "</description>\n";
			$xml .= "\t\t</course>\n";
		}
		$xml .= "\t</courses>\n";

		$xml .= "\t<lessons>\n";
		foreach ( $xml_data["lessons"] as $key=>$lesson )
		{
			$xml .= "\t\t<lesson id=\"" .$lesson->lesson_id. "\" course_id=\"" .$lesson->course_id. "\">\n";
			$xml .= "\t\t\t<title>";
			$xml .= $lesson->title;
			$xml .= "</title>\n";
			$xml .= "\t\t\t<description>";
			$xml .= $lesson->description;
			$xml .= "</description>\n";
			$xml .= "\t\t\t<url>";
			$xml .= $lesson->url;
			$xml .= "</url>\n";
			$xml .= "\t\t</lesson>\n";
		}
		$xml .= "\t</lessons>\n";

		return $xml;
	}

	private function write_xml($xml)
	{
		header('Content-Type:  application/xhtml+xml');
		header('Content-Disposition: attachment; filename='.$this->xml_filename.'');
		header('Content-Transfer-Encoding: binary');
		header('Content-Length: '.strlen($xml));
		echo $xml;
	}

}
?>

learn_yii/protected/controllers/ImportController.php
<?php
class ImportController extends Controller
{
	private $log;

	public function init() 
	{
		$this->log['messages'] = "";
		$this->log['errors'] = "";
	 }

	public function actionIndex()
	{
		$model = new Import;

		if ( isset( $_POST['Import'] ) )
		{
			$model->attributes = $_POST['Import'];
			if ( !empty($_FILES['Import']['tmp_name']['upload_file']) )
			{
				if ( $_FILES['Import']['type']['upload_file']  == 'text/xml' )
				{
					$file = CUploadedFile::getInstance( $model, 'upload_file' );

					$upload_filename = $_FILES['Import']['name']['upload_file'];
					$file->saveAs( Yii::getPathofAlias("webroot") ."/upload/".$upload_filename);

					$xml_file = Yii::getPathofAlias("webroot") ."/upload/". $_FILES['Import']['name']['upload_file'];
					$this->log['messages'][] = $xml_file . " was sucсessfuly uploaded ";

					$this->processImport( $xml_file );//start import
				}
				else
				{
					$this->log['errors'][]  = "Wrong filetype, only XML allowed.";
				}
			}
			else
			{
				$this->log['errors'][] = "Error uploaded ".$_FILES['Import']['name']['upload_file'];
			}
		}

		$params=array(
			"model"=>$model,
			'messages'=>$this->log['messages'],
			'errors'=>$this->log['errors'],
		);
		$this->render("index", $params );
	}

	private function processImport( $xml_file )
	{
		$this->log['messages'][] =  "start process import";
		if (file_exists($xml_file)) 
		{
			$xml = simplexml_load_file( $xml_file );
//echo "<pre>";
//print_r( $xml->courses );
//echo "</pre>";
//------------------------------------
/*
			$num = Courses::model()->deleteAll();
			$this->log['messages'][] =  "Table courses, deleted $num rows";

			$num = Lessons::model()->deleteAll();
			$this->log['messages'][] =  "Table lessons, deleted $num rows";
*/
			Yii::app()->db->createCommand()->truncateTable( Courses::model()->tableName() );
			$this->log['messages'][] =  "truncateTable courses";
			Yii::app()->db->createCommand()->truncateTable( Lessons::model()->tableName() );
			$this->log['messages'][] =  "truncateTable lessons";
//------------------------------------
			$model=new Courses;
			foreach ( $xml->courses->course as $key=>$course )
			{
				$model->isNewRecord = true;
				$model->course_id = $course["id"];
				$model->title = $course->title;
				$model->description = $course->description;
				$model->save();
			} //--------------- end foreach
			$this->log['messages'][] =  "Table Courses, inserted ".$model->count()." records";
//------------------------------------
			$model=new Lessons;
			foreach ( $xml->lessons->lesson as $key=>$lesson )
			{
				$model->isNewRecord = true;
				$model->lesson_id = null;
				$model->course_id = $lesson["course_id"];
				$model->url = $lesson->url;
				$model->title = $lesson->title;
				$model->description = $lesson->description;
				$model->save();
			} //--------------- end foreach
			$this->log['messages'][] =  "Table Lessons, inserted ".$model->count()." records";
		} 
		else 
		{
			$this->log['errors'][] =  "Failed to open $xml_file";
		}

	}//------------------------- end func


}
?>

learn_yii/protected/controllers/LessonController.php
<?php

class LessonController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			//'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view', 'list'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
//echo "public function actionView($id)";
//echo "<br>";

		$lesson = $this->loadModel($id);
		$course = Courses::model()->find("course_id = :course_id", array(":course_id" => $lesson->course_id));
		$this->render('view',array(
			'model'=>$lesson,
			'course'=>$course,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate(  )
	{
		if ( !empty($_REQUEST['course_id']) )
		{
			$course_id = Yii::app()->request->getParam('course_id');
		}
		else
			$course_id = 0;

		$course = Courses::model()->find("course_id = :course_id", array(":course_id" =>$course_id ));
		$courses = Courses::model()->findAll();
		$list = CHtml::listData( $courses, 'course_id', 'title' );

		$model=new Lessons;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Lessons']))
		{
			$model->attributes=$_POST['Lessons'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->lesson_id));
		}

		$this->render('create',array(
			'model'=>$model,
			'course'=>$course,
			'courses_list'=>$list,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$lesson=$this->loadModel($id);
		$course = Courses::model()->find("course_id = :course_id", array(":course_id" => $lesson->course_id));

		$courses = Courses::model()->findAll();
		//$list = array_values( CHtml::listData($courses, 'course_id', 'title') );
		$list = CHtml::listData( $courses, 'course_id', 'title' );

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Lessons']))
		{
/*
echo "<pre>";
print_r($_REQUEST);
echo "</pre>";
*/
			$lesson->attributes=$_POST['Lessons'];
			if($lesson->save())
				$this->redirect(array('view','id'=>$lesson->lesson_id));
		}

		$this->render('update',array(
			'model'=>$lesson,
			'course'=>$course,
			'courses_list'=>$list,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
//echo "public function actionIndex()";
//echo "<br>";
		$dataProvider=new CActiveDataProvider('Lessons');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Список уроков, не входящих в курсы
	 */
	public function actionList()
	{
//echo "public function actionList()";
//echo "<br>";
		$criteria = new CDbCriteria();
		$criteria->addInCondition('course_id', array('0') );
		$dataProvider=new CActiveDataProvider('Lessons', array('criteria' => $criteria) );
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Lessons('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Lessons']))
			$model->attributes=$_GET['Lessons'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Lessons the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Lessons::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Lessons $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='lessons-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

}//end class

learn_yii/protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

learn_yii/protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
</div>
<?php $this->endContent(); ?>

learn_yii/protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

	<title><?php echo CHtml::encode(Yii::app()->name); //echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo">
			<h2><a href="<?php echo Yii::app()->baseUrl?>"><?php echo CHtml::encode(Yii::app()->name); ?></a></h2>
		</div>
	</div><!-- header -->
<?php
//echo  Yii::app()->controller->id;
//echo "<br>";
//echo  Yii::app()->controller->action->id;
//echo "<br>";
$visible_course_item = true;
if ( Yii::app()->controller->id == "course" && Yii::app()->controller->action->id == "index" ) {
	$visible_course_item = false;
}
?>
	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				//array('label'=>'Home', 'url'=>array('/site/index'), 'visible'=>Yii::app()->controller->action->id != 'index' ),
array(
	'label'=>'Courses', 
	'url'=>array('/course/index'), 
	'visible'=>$visible_course_item,
/*
	'items'=>array
		(
		  array('label'=>'Добавить курс', 'url'=>array('/course/add')),
		)
*/
),
				array( 'label'=>'Unsort lessons', 'url'=>array('/lesson/list'), 'visible'=>Yii::app()->user->isGuest ),
				array( 'label'=>'Unsort lessons', 'url'=>array('/lesson/admin'), 'visible'=>!Yii::app()->user->isGuest ),
				array( 'label'=>'Export (xml format)', 
						'url'=>array('/export/export'),//, 'view'=>'index'), 
						'visible'=>!Yii::app()->user->isGuest ),

				array( 'label'=>'Import (xml format)', 	'url'=>array('/import/index', 'view'=>'index'), 'visible'=>!Yii::app()->user->isGuest ),

array('label'=>'Users', 'url'=>array('/users'), 'visible'=>!Yii::app()->user->isGuest, 'itemOptions'=>array('class' => 'topmenu-link right') ),

array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest, 'itemOptions'=>array('class' => 'topmenu-link right') ),
array('label'=>'Exit ('.Yii::app()->user->name.')', 
			'url'=>array('/site/logout'), 
			'visible'=>!Yii::app()->user->isGuest, 
			'itemOptions'=>array('class' => 'topmenu-link right'))
			),
		)); ?>
	</div><!-- mainmenu -->

	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
			'homeLink'=>false 
		)); ?><!-- breadcrumbs -->
	<?php endif?>

	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
<?php 
echo Yii::powered() ." ".Yii::getVersion() 
?>
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>